/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistem.autobuskastanica.forme;

import javax.swing.DefaultComboBoxModel;
import sistem.autobuskastanica.backendklase.AutobuskaLinija;
import sistem.autobuskastanica.backendklase.LabelAnimacija;
import sistem.autobuskastanica.backendklase.Zaposlen;

/**
 *
 * @author Darko
 */
public class DodavanjeLinijaForma extends javax.swing.JFrame {

    /**
     * Creates new form DodavanjeLinijaForma
     */
    private DodavanjeLinijaForma instanca;
    private Zaposlen vlasnikForme;
    
    public DodavanjeLinijaForma() {
        
        instanca = this;
        
        initComponents();
        
        ucitavanjeComboBoxeva();
        pocetneAnimacije();
        
    }
    
    public DodavanjeLinijaForma(Zaposlen zaposlen) {
        
        instanca = this;
        vlasnikForme = zaposlen;
        
        initComponents();
        
        ucitavanjeComboBoxeva();
        pocetneAnimacije();
        
    }
    
    private void pocetneAnimacije() {

        String gradPolazkaLabelaText = "Grad Polazka";
        String gradDolazkaLabelaText = "Grad Dolazka";
        String datumiLabela1Text = "Datumi";
        String datumiLabela2Text = "(DD.MM.GGGG jedan po liniji)";
        String vremenaLabela1Text = "Vremena";
        String vremenaLabela2Text = "(SS:MM jedno po liniji)";
        String sedistaLabelaText = "Sedista";
        String cenaLabelaText = "Cena";
        GradPolazkaLabela.setText("");
        GradDolazkaLabela.setText("");
        DatumiLabela1.setText("");
        DatumiLabela2.setText("");
        VremenaLabela1.setText("");
        VremenaLabela2.setText("");
        SedistaLabela.setText("");
        CenaLabela.setText("");
        LabelAnimacija.pokreni(GradPolazkaLabela, gradPolazkaLabelaText, 50, 0, 250);
        LabelAnimacija.pokreni(GradDolazkaLabela, gradDolazkaLabelaText, 50, 0, 250);
        LabelAnimacija.pokreni(DatumiLabela1, datumiLabela1Text, 50, 0, 250);
        LabelAnimacija.pokreni(DatumiLabela2, datumiLabela2Text, 50, 0, 250 + datumiLabela1Text.length() * 50);
        LabelAnimacija.pokreni(VremenaLabela1, vremenaLabela1Text, 50, 0, 250);
        LabelAnimacija.pokreni(VremenaLabela2, vremenaLabela2Text, 50, 0, 250 + vremenaLabela1Text.length() * 50);
        LabelAnimacija.pokreni(SedistaLabela, sedistaLabelaText, 50, 0, 250);
        LabelAnimacija.pokreni(CenaLabela, cenaLabelaText, 50, 0, 250);

    }
    
    private void ucitavanjeComboBoxeva(){
    
        DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addAll(AutobuskaLinija.dozvoljeniGradovi);
        jComboBox1.setModel(defaultComboBoxModel1);
        DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addAll(AutobuskaLinija.dozvoljeniGradovi);
        jComboBox2.setModel(defaultComboBoxModel2);    
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackLabela = new javax.swing.JLabel();
        GradPolazkaLabela = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        GradDolazkaLabela = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        DatumiLabela1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        DatumiLabela2 = new javax.swing.JLabel();
        VremenaLabela1 = new javax.swing.JLabel();
        VremenaLabela2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        SedistaLabela = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CenaLabela = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        DodajButton = new javax.swing.JButton();
        UnosenjeUspeloLabela = new javax.swing.JLabel();
        GradPolazkaLabela1 = new javax.swing.JLabel();
        GradDolazkaLabela1 = new javax.swing.JLabel();
        DatumiLabela3 = new javax.swing.JLabel();
        VremenaLabela3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(44, 44, 44));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));

        BackLabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        BackLabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabelaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackLabelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackLabelaMouseExited(evt);
            }
        });

        GradPolazkaLabela.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        GradPolazkaLabela.setForeground(new java.awt.Color(114, 137, 218));
        GradPolazkaLabela.setText("Grad Polazka");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        GradDolazkaLabela.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        GradDolazkaLabela.setForeground(new java.awt.Color(114, 137, 218));
        GradDolazkaLabela.setText("Grad Dolazka");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        DatumiLabela1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        DatumiLabela1.setForeground(new java.awt.Color(114, 137, 218));
        DatumiLabela1.setText("Datumi");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        DatumiLabela2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        DatumiLabela2.setForeground(new java.awt.Color(114, 137, 218));
        DatumiLabela2.setText("(DD.MM.GGGG jedan po liniji)");

        VremenaLabela1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        VremenaLabela1.setForeground(new java.awt.Color(114, 137, 218));
        VremenaLabela1.setText("Vremena");

        VremenaLabela2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        VremenaLabela2.setForeground(new java.awt.Color(114, 137, 218));
        VremenaLabela2.setText("(SS:MM jedno po liniji)");

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        SedistaLabela.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        SedistaLabela.setForeground(new java.awt.Color(114, 137, 218));
        SedistaLabela.setText("Sedista");

        CenaLabela.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        CenaLabela.setForeground(new java.awt.Color(114, 137, 218));
        CenaLabela.setText("Cena");

        DodajButton.setBackground(new java.awt.Color(114, 137, 218));
        DodajButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DodajButton.setText("Dodaj");

        UnosenjeUspeloLabela.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        UnosenjeUspeloLabela.setForeground(new java.awt.Color(0, 153, 51));

        GradPolazkaLabela1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        GradPolazkaLabela1.setForeground(new java.awt.Color(255, 51, 51));

        GradDolazkaLabela1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        GradDolazkaLabela1.setForeground(new java.awt.Color(255, 51, 51));

        DatumiLabela3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        DatumiLabela3.setForeground(new java.awt.Color(255, 51, 51));

        VremenaLabela3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        VremenaLabela3.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackLabela))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(VremenaLabela1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VremenaLabela2))
                            .addComponent(GradDolazkaLabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, 300, Short.MAX_VALUE)
                            .addComponent(GradPolazkaLabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DatumiLabela1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DatumiLabela2))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SedistaLabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CenaLabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DodajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UnosenjeUspeloLabela))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GradPolazkaLabela1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(GradDolazkaLabela1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DatumiLabela3)
                                    .addComponent(VremenaLabela3))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackLabela)
                .addGap(50, 50, 50)
                .addComponent(GradPolazkaLabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradPolazkaLabela1))
                .addGap(18, 18, 18)
                .addComponent(GradDolazkaLabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradDolazkaLabela1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatumiLabela1)
                    .addComponent(DatumiLabela2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatumiLabela3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VremenaLabela1)
                    .addComponent(VremenaLabela2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VremenaLabela3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SedistaLabela)
                    .addComponent(CenaLabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DodajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UnosenjeUspeloLabela)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackLabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelaMouseEntered
        
        BackLabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back2.png")));
        
    }//GEN-LAST:event_BackLabelaMouseEntered

    private void BackLabelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelaMouseExited
        
        BackLabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png")));
        
    }//GEN-LAST:event_BackLabelaMouseExited

    private void BackLabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelaMouseClicked
       
        RadnikForma radnikForma = new RadnikForma(vlasnikForme);
        radnikForma.setLocation(instanca.getLocation());
        radnikForma.setVisible(true);
        instanca.dispose();
        
    }//GEN-LAST:event_BackLabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodavanjeLinijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodavanjeLinijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodavanjeLinijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodavanjeLinijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DodavanjeLinijaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLabela;
    private javax.swing.JLabel CenaLabela;
    private javax.swing.JLabel DatumiLabela1;
    private javax.swing.JLabel DatumiLabela2;
    private javax.swing.JLabel DatumiLabela3;
    private javax.swing.JButton DodajButton;
    private javax.swing.JLabel GradDolazkaLabela;
    private javax.swing.JLabel GradDolazkaLabela1;
    private javax.swing.JLabel GradPolazkaLabela;
    private javax.swing.JLabel GradPolazkaLabela1;
    private javax.swing.JLabel SedistaLabela;
    private javax.swing.JLabel UnosenjeUspeloLabela;
    private javax.swing.JLabel VremenaLabela1;
    private javax.swing.JLabel VremenaLabela2;
    private javax.swing.JLabel VremenaLabela3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
