/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistem.autobuskastanica.forme;

import sistem.autobuskastanica.backendklase.LabelAnimacija;
import sistem.autobuskastanica.backendklase.Zaposlen;

/**
 *
 * @author danij
 */
public class RadnikForma extends javax.swing.JFrame {

    /**
     * Creates new form RadnikForma
     */
    private RadnikForma instanca;
    private Zaposlen vlasnikForme;
    
    public RadnikForma() {
        
        instanca = this;
        
        initComponents();
        
        pocetneAnimacije();
        
    }
    
    public RadnikForma(Zaposlen zaposlen) {
        
        instanca = this;
        vlasnikForme = zaposlen;
        
        initComponents();
        
        pocetneAnimacije();
        
    }
    
    private void pocetneAnimacije(){
    
        if(vlasnikForme == null) return;
    
        String Labela1Text = "RADNIK: " + vlasnikForme.getIme() + " " + vlasnikForme.getPrezime();
        Labela1.setText("");
        LabelAnimacija.pokreni(Labela1, Labela1Text, 25, 0, 250);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Labela1 = new javax.swing.JLabel();
        backLabela = new javax.swing.JLabel();
        IzdavanjeKarataButton = new javax.swing.JButton();
        StatusLinijaButton = new javax.swing.JButton();
        DodavanjeLinijaButton = new javax.swing.JButton();
        OstavljanjeStvariButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(44, 44, 44));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));

        Labela1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        Labela1.setForeground(new java.awt.Color(114, 137, 218));
        Labela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labela1.setText("RADNIK");

        backLabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        backLabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLabelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLabelaMouseExited(evt);
            }
        });

        IzdavanjeKarataButton.setBackground(new java.awt.Color(114, 137, 218));
        IzdavanjeKarataButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        IzdavanjeKarataButton.setForeground(new java.awt.Color(44, 47, 51));
        IzdavanjeKarataButton.setText("IZDAVANJE KARATA");
        IzdavanjeKarataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IzdavanjeKarataButton.setMaximumSize(new java.awt.Dimension(250, 30));
        IzdavanjeKarataButton.setMinimumSize(new java.awt.Dimension(250, 30));
        IzdavanjeKarataButton.setPreferredSize(new java.awt.Dimension(250, 30));
        IzdavanjeKarataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzdavanjeKarataButtonActionPerformed(evt);
            }
        });

        StatusLinijaButton.setBackground(new java.awt.Color(114, 137, 218));
        StatusLinijaButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        StatusLinijaButton.setForeground(new java.awt.Color(44, 47, 51));
        StatusLinijaButton.setText("STATISTIKA LINIJA");
        StatusLinijaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StatusLinijaButton.setMaximumSize(new java.awt.Dimension(250, 30));
        StatusLinijaButton.setMinimumSize(new java.awt.Dimension(250, 30));
        StatusLinijaButton.setPreferredSize(new java.awt.Dimension(250, 30));
        StatusLinijaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatusLinijaButtonMouseClicked(evt);
            }
        });

        DodavanjeLinijaButton.setBackground(new java.awt.Color(114, 137, 218));
        DodavanjeLinijaButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DodavanjeLinijaButton.setForeground(new java.awt.Color(44, 47, 51));
        DodavanjeLinijaButton.setText("DODAVANJE LINIJA");
        DodavanjeLinijaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DodavanjeLinijaButton.setMaximumSize(new java.awt.Dimension(250, 30));
        DodavanjeLinijaButton.setMinimumSize(new java.awt.Dimension(250, 30));
        DodavanjeLinijaButton.setPreferredSize(new java.awt.Dimension(250, 30));
        DodavanjeLinijaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodavanjeLinijaButtonActionPerformed(evt);
            }
        });

        OstavljanjeStvariButton.setBackground(new java.awt.Color(114, 137, 218));
        OstavljanjeStvariButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OstavljanjeStvariButton.setForeground(new java.awt.Color(44, 47, 51));
        OstavljanjeStvariButton.setText("OSTAVLJANJE STVARI");
        OstavljanjeStvariButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OstavljanjeStvariButton.setMaximumSize(new java.awt.Dimension(250, 30));
        OstavljanjeStvariButton.setMinimumSize(new java.awt.Dimension(250, 30));
        OstavljanjeStvariButton.setPreferredSize(new java.awt.Dimension(250, 30));
        OstavljanjeStvariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OstavljanjeStvariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Labela1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLabela))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DodavanjeLinijaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(OstavljanjeStvariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IzdavanjeKarataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(StatusLinijaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabela)
                .addGap(18, 18, 18)
                .addComponent(Labela1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IzdavanjeKarataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusLinijaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DodavanjeLinijaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OstavljanjeStvariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IzdavanjeKarataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzdavanjeKarataButtonActionPerformed
        
        IzdavanjeKarataForma izdavanjeKarataForma = new IzdavanjeKarataForma(vlasnikForme);
        izdavanjeKarataForma.setLocation(instanca.getLocation());
        izdavanjeKarataForma.setVisible(true);
        instanca.dispose();
        
    }//GEN-LAST:event_IzdavanjeKarataButtonActionPerformed

    private void DodavanjeLinijaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodavanjeLinijaButtonActionPerformed
        
        DodavanjeLinijaForma dodavanjeLinijaForma = new DodavanjeLinijaForma(vlasnikForme);
        dodavanjeLinijaForma.setLocation(instanca.getLocation());
        dodavanjeLinijaForma.setVisible(true);
        instanca.dispose();
        
    }//GEN-LAST:event_DodavanjeLinijaButtonActionPerformed

    private void OstavljanjeStvariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OstavljanjeStvariButtonActionPerformed
       
        OstavljanjeStvariForma ostavljanjeStvariForma = new OstavljanjeStvariForma(vlasnikForme);
        ostavljanjeStvariForma.setLocation(instanca.getLocation());
        ostavljanjeStvariForma.setVisible(true);
        instanca.dispose();
        
    }//GEN-LAST:event_OstavljanjeStvariButtonActionPerformed

    private void backLabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelaMouseEntered
        
        backLabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back2.png")));
        
    }//GEN-LAST:event_backLabelaMouseEntered

    private void backLabelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelaMouseExited
        
        backLabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png")));
        
    }//GEN-LAST:event_backLabelaMouseExited

    private void backLabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelaMouseClicked
        
        LoginForma loginForma = new LoginForma();
        loginForma.setLocation(instanca.getLocation());
        loginForma.setVisible(true);
        instanca.dispose();
        
    }//GEN-LAST:event_backLabelaMouseClicked

    private void StatusLinijaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusLinijaButtonMouseClicked
        
        StatistikaLinijaForma statistikaLinijaForma = new StatistikaLinijaForma(vlasnikForme);
        statistikaLinijaForma.setLocation(instanca.getLocation());
        statistikaLinijaForma.setVisible(true);
        instanca.dispose();
        
    }//GEN-LAST:event_StatusLinijaButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadnikForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodavanjeLinijaButton;
    private javax.swing.JButton IzdavanjeKarataButton;
    private javax.swing.JLabel Labela1;
    private javax.swing.JButton OstavljanjeStvariButton;
    private javax.swing.JButton StatusLinijaButton;
    private javax.swing.JLabel backLabela;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
